[post] 2021-10-18-p-vs-np
mathsociitd/blog pull request #11
Opened 2021-10-11 17:55 UTC by tushar1810

**ToDo:**
- [x] Fix tags
- [x] Extra space before comma (`<space>,<space> ` -> `,<space>`)
- [x] `#`, `##`, ... are headings.. they appear at Contents in the right (like ToC).. Make use of them to make different sections...
---
- [x] `"xyz,"` -> `"xyz",`
---
- [x] Changing the date (before merging) 
- [x] Update file and media names according to date

2021-10-12 06:34 UTC, subhalingamd requested changes
looks great.. some minor suggestions here.. 😄

2021-10-12 06:34 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +  - indecipherable
also add these in the beginning..
- article
- mathematics-in-focus

2021-10-12 06:34 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +  - attempts in vain
attempts-in-vain
(use ifins in tags)

2021-10-12 06:34 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +Not to break "blog" rules and simultaneously to give direction to your enthusiasm , reader can visit https://arxiv.org/ftp/arxiv/papers/1911/1911.00722.pdf that contains Razborov's attempt in more de
Use the `[]()`/`<a>` syntax for URLs

2021-10-12 06:34 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +* Daring Diagonalisation
these are section headings right? try to use the headings syntax if possible?

2021-10-12 06:49 UTC, subhalingamd requested changes

2021-10-12 06:49 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +___
why is this here?

2021-10-13 17:10 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> +_**Hey!**_ fabulous moment you took a stop at this one :tada: :tada: .as maybe after this 5min read , your life and consequently world may change in a positive way! Not only I am tempting your dollar
Change to the following:

Welcome. Take a seat. We have been awaiting your arrival for quite a long time. We are presenting you with an opportunity of a lifetime, an opportunity that may completely change your life. Not only are we tempting your inner avarice by providing you with a chance to win a million dollars from the Clay Mathematics Institute, but also letting you know that if you solve this problem:

2021-10-13 17:17 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> + Lets dig a bit deeper into this. P is a class of problems which human race has solved quickly and efficiently ,by being “efficient” I mean algorithms of these problems can compute in polynomial time
- ~Lets~ Let's
- fix spacing, a few commas/prepositions missing (run the paragraph/sentences on grammarly)
- "four options available to ~tick~ consider"

2021-10-13 17:18 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> +general circuits one will have proved P!=NP , however later Roborov himself diagress with previous results if NOT gate is also taken into consideration.
run grammarly

2021-10-13 17:19 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> +    * This famous technique in mathematics was first used by Cantor to prove real numbers are uncountable.Turing, in his seminal paper on computation , used a similar technique to show that the Halti
run grammarly

2021-10-13 17:22 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> +Not to break "blog" rules and simultaneously to give direction to your enthusiasm , reader can visit https://arxiv.org/ftp/arxiv/papers/1911/1911.00722.pdf that contains Razborov's attempt in more de
Replace by:

Are you ready to undertake the challenge of delving further into this predicament? Check out [Razborov's attempt in more detail](https://arxiv.org/ftp/arxiv/papers/1911/1911.00722.pdf), and check out a [deeper description of diagonalization](http://courses.csail.mit.edu/6.841/spring09/scribe/lect02.pdf).

2021-10-14 04:56 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +general circuits one will have proved P!=NP , however later Roborov himself diagress with previous results if NOT gate is also taken into consideration.
also, use $\ne$ sign rather than `!=`..? we are mathematicians :/

2021-10-15 13:43 UTC, subhalingamd requested changes

2021-10-15 13:43 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +>### *Does P equals NP? after “how humans evolved” this is the biggest ques , Darwin of which is yet to be discovered.*
Fix `<space>,<space>` here

2021-10-15 13:43 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +>* This doesn’t end here, there are literally more spellbinding tasks which can bring an absolutely updated version of Earth. I am extremely sorry if your business entirely depends on crypto-related
i guess each bullet should be independent..shouldn't end with `,` or `and` imo
and the last point is too long... 

@khushipathak your opinions?

2021-10-15 13:43 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> + Let's dig a bit deeper into this. P is a class of problems which human race has solved quickly and efficiently; by being “efficient” I mean algorithms of these problems can compute in polynomial tim
fix `<space>:` to `:`
ps: why do you leave a space before punctuation? :P pls verify this in other places too..

2021-10-15 13:54 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +>* This doesn’t end here, there are literally more spellbinding tasks which can bring an absolutely updated version of Earth. I am extremely sorry if your business entirely depends on crypto-related
also, whats that > doing in-between the text??
e.g. *`>never before`*

2021-10-15 13:58 UTC, khushipathak commented on _posts/2021-10-11-pvsnp.md
> + Let's dig a bit deeper into this. P is a class of problems which human race has solved quickly and efficiently; by being “efficient” I mean algorithms of these problems can compute in polynomial tim
please fix the clarity of this paragraph. This forms the crux of the post but is a little difficult to follow through. Put it in grammarly or prowritingaid.com.

If you want, you can split the paragraph into 2 smaller paragraphs for better readability

2021-10-16 13:21 UTC, subhalingamd requested changes

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +>* the biggest bait of all is that you can crack 10700 levels of Candy Crush with ease and can become the **Universe boss**.
when first two points start with uppercase why not the third one too? you need to be too formal but the syntax shouldn't go wrong..

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +This doesn’t end here; there are more spellbinding tasks that can bring an updated version of Earth. I am incredibly sorry if your business entirely depends on crypto-related algorithms as, if someho
This doesn't end here can be another point.. one point cannot be way longer than the rest.. 
or take it outside the list and start a new para..

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +>### *Does P equals NP? after “how humans evolved,” this is the biggest ques, Darwin of which is yet to be discovered.*
“how humans evolved,” -> “how humans evolved”,
??

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +Are you ready to undertake the challenge of delving further into this predicament? Check out <a href="https://arxiv.org/ftp/arxiv/papers/1911/1911.00722.pdf"> Razborov's attempt in more detail</a>, a
try to add all the references?
e.g. "first used by Cantor to prove real numbers..", "In his seminal paper on computation, Turing used a similar technique..."

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> + * <h5>Razborov's "almost" Robust attempt</h5>
can you remove the bullets and also use `#####` instead of `<h5>...</h5>`? ? ToC anchors dont seem to work.. :/ 
maybe probably that's the issue..

ps: remove the bullets in the subsequent content too...

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +    * It has been proved that small circuits cannot solve the parity function if the circuits have a fixed number of layers of gates. Razborov showed the NP-complete problem of finding a large clique
remove the bullet in line 32 if you are removing the bullet above...

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +* <h5>Daring Diagonalisation</h5>
can you remove the bullets and also use `#####` instead of `<h5>...</h5>`? ? ToC anchors dont seem to work.. :/ 
maybe probably that's the issue..

ps: remove the bullets in the subsequent content too...

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +    * This famous technique in mathematics was first used by Cantor to prove real numbers are uncountable. In his seminal paper on computation, Turing used a similar technique to show that the Haltin
remove the bullet in line 35 if you are removing the bullet above...

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> + <img src="/blog/media/post/2021-10-11-pvsnp_img.png" alt="nothing">
please give credits to the image if its not yours..

2021-10-16 13:21 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +  Let's dig a bit deeper into this. P is a class of problems that the human race has solved quickly and efficiently; by being “efficient,” I mean algorithms of these problems can be computed in polyn
“efficient,” -> “efficient”,
@khushipathak ?
[ps: fix all of these please

2021-10-18 06:13 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> +date: 2021-10-11 11:00:17 +0530
`date: 2021-10-18 17:00:00 +0530`

2021-10-18 06:15 UTC, subhalingamd commented on _posts/2021-10-11-pvsnp.md
> + <img src="/blog/media/post/2021-10-11-pvsnp_img.png" alt="nothing">
change media path accordingly...

2021-10-18 11:30 UTC, merged