Mihir edits
mathsociitd/blog pull request #7
Opened 2021-04-08 17:39 UTC by Mihirokte

2021-04-08 17:46 UTC, subhalingamd requested changes

2021-04-08 17:46 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +  In this article we are going to talk about an interesting cyclic phenomena of the Fibonacci Numbers.
Remove the indentation at the beginning

2021-04-08 17:46 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +2
Make this as ordered-list..
```
1. ...
2. ...
```

2021-04-08 17:46 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +<br/>  The Fibonacci numbers are the numbers in the integer sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, ... defined by the recurrence relation
Italics?

2021-04-08 17:46 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +⇒ *R<sub>m+2</sub> = R<sub>n+2</sub> <br/>*
`<center> ... </center>` ??

2021-04-08 17:46 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +### How? Here's the proof:
Better heading? Or make it just as a bold word?

2021-04-09 05:48 UTC, Mihirokte commented on _posts/2021-04-04-fibonacci.md
> +<br/>  The Fibonacci numbers are the numbers in the integer sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, ... defined by the recurrence relation
kaha par? italics

2021-04-09 05:51 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +<br/>  The Fibonacci numbers are the numbers in the integer sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, ... defined by the recurrence relation
> The Fibonacci numbers are the numbers in the integer sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, ... defined by the recurrence relation

also do remove the leading whitespace.. it appears as indentation..

2021-04-09 05:52 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +<br/>  The Fibonacci numbers are the numbers in the integer sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, ... defined by the recurrence relation
Or enclose it in a `<div>...</div>` box..?

2021-04-09 05:56 UTC, Mihirokte commented
Done the changes, have a look

2021-04-09 06:08 UTC, subhalingamd requested changes

2021-04-09 06:08 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +date: 2021-04-04 21:03:16 +0530
Will have to change the `date`.. will gbty soon on this...

2021-04-09 06:08 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +  - fibonacci sequences
Use `-` instead of ` ` for a tag...
`fibonacci numbers` >> `fibonacci-numbers` 
...

2021-04-09 06:08 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +---
Embed the video before Intro...
Sample:
```
<video width="100%" controls>
<source src="{{ site.baseurl }}/media/post/2021-03-14-irrationality-of-nth-roots-promo.mp4" type="video/mp4">
</video>
```

2021-04-09 06:22 UTC, subhalingamd requested changes

2021-04-09 06:22 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +<source src="{{ site.baseurl }}/media/post/2021-03-14-irrationality-of-nth-roots-promo.mp4" type="video/mp4">
Add this post's video here.. lol.
upload them in `media/post/` with a similar formatting as the prev one..

2021-04-09 09:52 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +date: 2021-04-04 21:03:16 +0530
> Will have to change the `date`.. will gbty soon on this...

Change it to `2021-04-09 17:00:00 +0530`
Also rename the post as `2021-04-09-fibonacci.md` and the video accordingly..

2021-04-09 10:43 UTC, subhalingamd commented on _posts/2021-04-04-fibonacci.md
> +date: 2021-04-04 21:03:16 +0530
@Mihirokte file name...

2021-04-09 10:56 UTC, subhalingamd approved these changes

2021-04-09 10:59 UTC, subhalingamd commented
LGTM.. 

(Cc: #6)

2021-04-09 10:59 UTC, merged